[package]
name = "pointer-scan"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read-process-memory = "0.1.2"
procfs = "0.8.0"
libc = "0.2.73"
